In [1]:
import numpy as np

In [2]:
arr = np.random.rand(2,2)

In [3]:
arr

array([[0.69744619, 0.28090991],
       [0.02344533, 0.22795062]])

In [4]:
full = np.full((2,2),5)

In [5]:
full

array([[5, 5],
       [5, 5]])

In [6]:
zeros = np.zeros((3,3,3))

In [7]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [8]:
arr3 = np.random.rand(3,2,3)

In [9]:
arr3

array([[[0.4912856 , 0.33403205, 0.3290756 ],
        [0.56038309, 0.48014424, 0.76333132]],

       [[0.2751151 , 0.36132153, 0.65530517],
        [0.40903798, 0.17492567, 0.43283671]],

       [[0.10731608, 0.6604694 , 0.33624383],
        [0.46645246, 0.26787281, 0.90446652]]])

In [10]:
arr3[2][0][1]

np.float64(0.6604693960453824)

In [15]:
arr2 = np.random.randint(int(3,2,3))

TypeError: int expected at most 2 arguments, got 3

In [14]:
arr2 = int(np.random.rand(3,3,3))

TypeError: only 0-dimensional arrays can be converted to Python scalars

In [16]:
a = np.random.randint(3,2,3)

ValueError: low >= high

In [18]:
a = np.random.random_integers(2,2)

C:\Users\SIVANESH\AppData\Local\Temp\ipykernel_17268\4274580924.py:1: DeprecationWarning: This function is deprecated. Please call randint(2, 2 + 1) instead
  a = np.random.random_integers(2,2)


In [19]:
a

np.int32(2)

In [20]:
a = np.random.default_rng().integers(1,100,size=(3,2,3))

In [21]:
a

array([[[89, 32, 15],
        [57, 38, 25]],

       [[44,  3, 53],
        [59, 13, 31]],

       [[15, 87, 46],
        [37, 61,  4]]])

In [22]:
np.min(a)

np.int64(3)

In [23]:
np.max(a)

np.int64(89)

In [1]:
a3 = np.zeroes[(2,2)]

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
a3 = np.zeros[(2,2)]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [6]:
a3 = np.zeros((2,2))

In [7]:
a3

array([[0., 0.],
       [0., 0.]])

In [8]:
a4 = np.ones((2,2,3))

In [9]:
a4

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [21]:
a5 = np.ones((2,2))

In [22]:
appd = np.append(a3,a5,axis=0)

In [23]:
appd

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [24]:
ina = np.insert(a3, 1, a5, axis=0)

In [25]:
ina

array([[0., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.]])

In [26]:
np.delete(a4)

TypeError: delete() missing 1 required positional argument: 'obj'

In [27]:
np.delete(a4,0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
np.delete(a4,1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
np.delete(a4,0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
clear

In [31]:
cls

In [32]:
np.save("array",a3)

In [33]:
np.load("array.npy")

array([[0., 0.],
       [0., 0.]])